[package]
name = "default"
version = "0.1"
lean_version = "leanprover-community/lean:3.48.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "c2d9927ee1c326fc044ac041a5aa39bb18539d32"}
